# Generated by Django 4.2 on 2025-02-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
